Drop Table IF Exists minutas

CREATE TABLE minutas
(
	datum int UNIQUE NOT NULL,
	pac_1 int NOT NULL,
	daySum_1 int NOT NULL,
	status_1 int NOT NULL,
	pac_2 int NOT NULL,
	daySum_2 int NOT NULL,
	status_2 int NOT NULL,
	error_2 int NOT NULL,
	pdc1_2 int NOT NULL,
	pdc2_2 int NOT NULL,
	pdc3_2 int NOT NULL,
	udc1_2 int NOT NULL,
	udc2_2 int NOT NULL,
	udc3_2 int NOT NULL,
	uac_2 int NOT NULL,
	pac_3 int NOT NULL,
	daySum_3 int NOT NULL,
	status_3 int NOT NULL,
	error_3 int NOT NULL,
	pdc1_3 int NOT NULL,
	pdc2_3 int NOT NULL,
	pdc3_3 int NOT NULL,
	udc1_3 int NOT NULL,
	udc2_3 int NOT NULL,
	udc3_3 int NOT NULL,
	uac_3 int NOT NULL,
	pac_4 int NOT NULL,
	daySum_4 int NOT NULL,
	status_4 int NOT NULL,
	error_4 int NOT NULL,
	pdc1_4 int NOT NULL,
	pdc2_4 int NOT NULL,
	pdc3_4 int NOT NULL,
	udc1_4 int NOT NULL,
	udc2_4 int NOT NULL,
	udc3_4 int NOT NULL,
	uac_4 int NOT NULL,
	pac_5 int NOT NULL,
	daySum_5 int NOT NULL,
	status_5 int NOT NULL,
	error_5 int NOT NULL,
	pdc1_5 int NOT NULL,
	pdc2_5 int NOT NULL,
	pdc3_5 int NOT NULL,
	udc1_5 int NOT NULL,
	udc2_5 int NOT NULL,
	udc3_5 int NOT NULL,
	uac_5 int NOT NULL,
	pac_6 int NOT NULL,
	daySum_6 int NOT NULL,
	status_6 int NOT NULL,
	error_6 int NOT NULL,
	pdc1_6 int NOT NULL,
	pdc2_6 int NOT NULL,
	pdc3_6 int NOT NULL,
	udc1_6 int NOT NULL,
	udc2_6 int NOT NULL,
	udc3_6 int NOT NULL,
	uac_6 int NOT NULL,
	pac_7 int NOT NULL,
	daySum_7 int NOT NULL,
	status_7 int NOT NULL,
	error_7 int NOT NULL,
	pdc1_7 int NOT NULL,
	pdc2_7 int NOT NULL,
	pdc3_7 int NOT NULL,
	udc1_7 int NOT NULL,
	udc2_7 int NOT NULL,
	udc3_7 int NOT NULL,
	uac_7 int NOT NULL,
)

CREATE INDEX IX_datum
ON minutas (datum)
INCLUDE (
pac_1,
	daySum_1,
	status_1,
	pac_2,
	daySum_2,
	status_2,
	error_2,
	pdc1_2,
	pdc2_2,
	pdc3_2,
	udc1_2,
	udc2_2,
	udc3_2,
	uac_2,
	pac_3,
	daySum_3,
	status_3,
	error_3,
	pdc1_3,
	pdc2_3,
	pdc3_3,
	udc1_3,
	udc2_3,
	udc3_3,
	uac_3,
	pac_4,
	daySum_4,
	status_4,
	error_4,
	pdc1_4,
	pdc2_4,
	pdc3_4,
	udc1_4,
	udc2_4,
	udc3_4,
	uac_4,
	pac_5,
	daySum_5,
	status_5,
	error_5,
	pdc1_5,
	pdc2_5,
	pdc3_5,
	udc1_5,
	udc2_5,
	udc3_5,
	uac_5,
	pac_6,
	daySum_6,
	status_6,
	error_6,
	pdc1_6,
	pdc2_6,
	pdc3_6,
	udc1_6,
	udc2_6,
	udc3_6,
	uac_6,
	pac_7,
	daySum_7,
	status_7,
	error_7,
	pdc1_7,
	pdc2_7,
	pdc3_7,
	udc1_7,
	udc2_7,
	udc3_7,
	uac_7
)
